Added solution for the task 1
sayumikko/formal-lang-course pull request #1
Opened 2023-09-12 09:11 UTC by sayumikko

2023-09-13 18:00 UTC, vadyushkins requested changes

2023-09-13 18:00 UTC, vivalerievich commented on .github/workflows/run_test.yml
> +    runs-on: ubuntu-latest
windows, macos

2023-09-13 18:00 UTC, vivalerievich commented on project/__main__.py
> +    main()
?

2023-09-13 18:00 UTC, vivalerievich commented on project/graph_module.py
> +import networkx as nkx
```suggestion
import cfpq_data
import networkx as nx
```

2023-09-15 19:22 UTC, vadyushkins approved these changes

2023-09-16 17:35 UTC, merged